version: '3.9'
services:
  postgres:
    container_name: 'agreena-db'
    image: postgres:14.2
    env_file:
      - .env.local
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    environment:
      - 'POSTGRES_USER=${DATABASE_USER}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
      - 'POSTGRES_DB=${DATABASE_DB}'
    volumes:
      - 'DBData:/var/lib/postgresql/data'

volumes:
  DBData:
    name: agreenaDB
