version: '3.9'
services:
  postgres:
    container_name: 'agreena-test-db'
    image: postgres:14.2
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    environment:
      - 'POSTGRES_USER=${DATABASE_USER}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
      - 'POSTGRES_DB=${DATABASE_DB}'
